//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgencyEntities : DbContext
    {
        public TravelAgencyEntities()
            : base("name=TravelAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Excursions> Excursions { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Tour_Guides> Tour_Guides { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<UserAuth> UserAuth { get; set; }
    }
}
